<?php
/**
 * app/views/floor-plans/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'Floor Plans'));
?>
<div id="main-body">
    <h2 class="title-alt">James Madison Memorial Building</h2>
	<ul>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=6&b=Madison">Sixth Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=5&b=Madison">Fifth Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=4&b=Madison">Fourth Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=3&b=Madison">Third Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=2&b=Madison">Second Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=1&b=Madison">First Floor </a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=9&b=Madison">Ground Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=8&b=Madison">Basement</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=7&b=Madison">Sub-Basement </a></li>
	</ul>

	<h2 class="title-alt">John Adams Building</h2>
	<ul>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=19&b=Adams">Fifth Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=18&b=Adams">Fourth Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=17&b=Adams">Third Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=16&b=Adams">Second Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=15&b=Adams">First Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=14&b=Adams">Basement/Ground Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=25&b=Adams">Sub-Basement</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=13&b=Adams">Cellar</a></li>
	</ul>

	<h2 class="title-alt">Thomas Jefferson Building</h2>
	<ul>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=20&b=Jefferson">Upper Third Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=23&b=Jefferson">Third Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=12&b=Jefferson">Second Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=11&b=Jefferson">First Floor</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=21&b=Jefferson">Cellar</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=22&b=Jefferson">Ground Floor</a></li>
	</ul>

	<h2 class="title-alt">Taylor Street Annex</h2>
	<ul>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=27&b=Taylor+Street ">Upper Level</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php?m=r&f=28&b=Taylor+Street">Lower Level</a></li>
	</ul>


	<h2 class="title-alt">Related Links</h2>
	<ul>
		<li><a href="http://www.loc.gov/visit/maps/">Maps and Photos of Buildings from Public Site</a></li>
		<li><a href="http://www.loc.gov/staff/epp/index.php">Emergency Preparedness Program / Action Plans</a></li>
		<li><a href="http://www.loc.gov/staff/buildings/buildingaccess.html">Building Access Hours</a></li>
	</ul>

    <p><a href="#" class="top">Top</a></p>
</div>
