<?php
/**
 * app/views/standard-disclaimer/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'Standard Disclaimer for External Links'));
?>
<div id="main-body">
    <p>These links are being provided as a convenience and for information purposes only; they do not constitute an endorsement or an approval by the Library of Congress of any products, services or opinions of the corporation or organization or individual. The Library of Congress bears no responsibility for the accuracy, legality or content of the external site or for that of its subsequent links. Contact the external site for answers to questions regarding its content.</p>

	<p>
	    <b>Please note:</b> Web pages on the Library of Congress Site containing one or more links to external Internet sites may carry the above statement, in its entirety. However, in some cases they will display the following icon which links to this page:<br /><br />
	    <img src="/img/disclaimer.gif" alt="Disclaimer" />
    </p>

    <p><a href="#" class="top">Top</a></p>
</div>
