<?php
/**
 * app/views/auth/login.phtml
 *
 * @package Views
 * @author  aidan lydon <aidanlydon@gmail.com>
 */
?>
<div id="main-body">
    <?php if (!empty($errors)) {
        echo '<ul class="error-msg"><li>' . implode('</li><li>', $errors) . '</li></ul>';
    } ?>

    <form method="post">
        <label for="username">Username</label>
        <input type="text" id="username" name="username" value="<?php echo out($data['username']); ?>"/>
        <label for="password">Password</label>
		<input type="password" id="password" name="password"/>
		<input type="submit" value="Submit"/>
	</form>
</div>
