<?php
/**
 * app/views/intranets/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'Division & Service Unit Intranets'));
?>
<div id="main-body">

    TODO: intranets

    <p><a href="#" class="top">Top</a></p>
</div>
