<?php
/**
 * app/views/index/_item.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
echo '<li>';
if ($item['url']) {
    if ($item['external']) {
        echo '<a class="external" href="' . out($item['url']) . '" title="external link" target="_blank">' . out($item['title']) . '<span>(external link)</span></a> ' . out($item['pdfInfo']);
    } else {
        if ($item['title'] == 'see all divisional intranets') {
            //SPECIAL CASE for see all divisional intranets
            echo '<strong>';
        }

        echo '<a href="' . out($item['url']) . '" title="link: ' . out($item['url']) . '">' . out($item['title']) . '</a> ' . out($item['pdfInfo']);

        if ($item['title'] == 'see all divisional intranets') {
            echo '</strong>';
        }
	}
} else {
    //it's a phone number
    $spanClass = 'ext';
    if ($item['multiLine']) {
        $spanClass .= ' ld';
    }

    echo '<div class="toc"><span class="' . out($spanClass) . '">' . out($item['phone']) . '</span><span class="info">' . out($item['title']) . '</span></div>';
}
echo '</li>';
