<?php
/**
 * app/views/index/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
?>
<div id="box-mylinks">
    <div id="quicklinks">
        <div id="quicklinks-column1">
            <h2>Quick Links</h2>
            <p class="line">&nbsp;</p>
            <p class="std">Easy access to frequently visited staff pages</p>
        </div>

        <div id="quicklinks-column2">
            <ul id="col1">
            <?php
            for ($i = 0; $i < 5; $i++) {
                $this->partial('index/_myLink', array('link' => $data['myLinks'][$i]));
            }
            ?>
			</ul>
			<ul id="col2">
			<?php
			for ($i = 5; $i < 10; $i++) {
                $this->partial('index/_myLink', array('link' => $data['myLinks'][$i]));
            }
            ?>
			</ul>
		</div>
    </div>
</div>

<div id="box-tabber">
    <ul class="tabNavigation">
        <li class="first"><a href="#first"<?php if ($data['settings']['Active_Tab'] == 'first') { echo ' class="selected"'; } ?>>Announce</a></li>
        <li class="second"><a href="#second"<?php if ($data['settings']['Active_Tab'] == 'second') { echo ' class="selected"'; } ?>>News</a></li>
        <li class="third"><a href="#third"<?php if ($data['settings']['Active_Tab'] == 'third') { echo ' class="selected"'; } ?>>Link of the Week</a></li>
    </ul>

    <div id="first">
    <?php if ($data['currentAnnouncement'] != false) { ?>
        <h4><?php echo out($data['currentAnnouncement']->title); ?></h4>
        <p>
            <em><?php echo out(date('m-d-Y', strtotime($data['currentAnnouncement']->dateTime))); ?></em>
            <?php echo out($data['currentAnnouncement']->excerpt); ?> -
    <?php } else { ?>
        <p>
    <?php } ?>
            [<a href="/announcements">More</a>]
        </p>
    </div>

    <div id="second">
    <?php if ($data['currentNews'] != false) { ?>
        <h4><?php echo out($data['currentNews']->title); ?></h4>
        <p>
            <em><?php echo out(date('m-d-Y', strtotime($data['currentNews']->dateTime))); ?></em>
            <?php echo out($data['currentNews']->excerpt); ?> -
    <?php } else { ?>
        <p>
    <?php } ?>
            [<a href="/news">More</a>]
        </p>
    </div>

    <div id="third">
    <?php if ($data['linkOfTheWeek'] != false) { ?>
        <h4><a href="<?php echo out($data['linkOfTheWeek']->url); ?>"><?php echo out($data['linkOfTheWeek']->title); ?></a></h4>
        <p>
            <em><?php echo out(substr($data['linkOfTheWeek']->description, 0, 100)); ?></em>
    <?php } else { ?>
        <p>
    <?php } ?>
            [<a href="/link-of-the-week/suggest">Suggest</a>] [<a href="/link-of-the-week">Archive</a>]
        </p>
    </div>
</div>

<p class="date"><?php echo out(date('l, F d, Y | h:i A')); ?></p>

<div id="box-widget">
    <div id="widget-staffdir">
        <form action="http://www.loc.gov/staffcsd/staff/results.html" method="post">
            <label for="lname">Staff Directory</label>
            <input id="lname" name="lname" type="text" tabindex="1" value="Search last name" onfocus="value=''" />
            <input id="searchBy" name="searchBy" type="hidden" tabindex="2" value="name" />
            <input class="button" id="search_button" name="search_button" type="submit" value="GO" /> <a href="http://www.loc.gov/staffcsd/staff/index.html" target="_blank">Advanced</a>
        </form>
    </div>
    <div id="widget-links">
        <ul>
            <li class="weather"><a href="http://forecast.weather.gov/MapClick.php?CityName=Washington&amp;state=DC&amp;site=LWX&amp;textField1=38.895&amp;textField2=-77.0373&amp;e=1" target="_blank" title="external link"><span class="underline">Weather</span><span class="external2">&nbsp;</span></a></li>
            <li class="cam"><a href="http://app.ddot.dc.gov/" target="_blank" title="external link"><span class="underline">Street Cams</span><span class="external2">&nbsp;</span></a></li>
            <li class="metro"><a href="http://www.wmata.com/rider_tools/metro_service_status/rail_Bus.cfm" target="_blank" title="external link"><span class="underline">Metro</span><span class="external2">&nbsp;</span></a></li>
            <li class="traffic"><a href="http://traffic.yahoo.com/map?q1=Washington,%20DC%20us&amp;mag=5&amp;trf=1&amp;ard=1#mvt=m&amp;lat=38.886762&amp;lon=-77.052902&amp;mag=5&amp;zoom=14&amp;trf=1&amp;q1=Washington%2C%20DC%20us" target="_blank" title="external link"><span class="underline">Traffic</span><span class="external2">&nbsp;</span></a></li>
        </ul>
    </div>
</div>

<?php foreach ($data['sections'] as $section) {?>
<div id="box-<?php echo out($section['divId']); ?>">
	<h2><?php echo out($section['heading']); ?></h2>
	<div><img src="/img/img-<?php echo out($section['divId']); ?>.jpg" height="56" width="290" border="0" alt=""/></div>

	<div id="<?php echo out($section['divId']); ?>">
	<?php
	foreach ($section['subsections'] as $sub) {
	    if ($sub['id'] == 2) {
	        //SPECIAL CASE for Division & Service Unit Intranets
	        echo '<div class="worktools-servunits-outter"><div class="worktools-servunits-inner">';
	    }

	    if (!empty($sub['heading'])) {
	        echo '<h3>' . out($sub['heading']) . '</h3>';
	    }

	    $i = 0;
		foreach ($sub['groups'] as $group) {
		    echo '<ul>';

		    if (!empty($group['heading'])) {
		        if ($i == 0) {
    		        echo '<li class="subhead first">';
    		        $i++;
    		    } else {
    		        echo '<li class="subhead">';
    		    }
    		    echo out($group['heading']) . '<ul>';
		    }

		    foreach ($group['items'] as $item) {
		        $this->partial('index/_item', array('item' => $item));
		    }

		    if (!empty($group['heading'])) {
		        echo '</ul></li>';
		    }

		    echo '</ul>';
		}

		if ($sub['id'] == 2) {
		    //SPECIAL CASE for Division & Service Unit Intranets
	        echo '</div></div>';
	    }
	}
	?>
	</div>
</div>
<?php } ?>
