<?php
/**
 * app/views/page/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => $data['head']));
$this->partial('partial/banner', array('banner' => $data['banner']));
?>
<div id="main-body">
    <?php foreach ($data['items'] as $item) {
        if ($item['externalLink'] == 'Y') { ?>
            <h3 class="entry-title">
                <a class="external" href="<?php echo out($item['url']); ?>" title="External link: <?php echo out($item['url']); ?>"><?php echo out($item['title']); ?><span>(external link)</span></a><?php echo out($item['pdfInfo']); ?>
            </h3>
            <p class="entry-content"><?php echo out($item['description']); ?></p>
        <?php } elseif (empty($item['url'])) { ?>
            <h3 class="entry-title"><?php echo out($item['title']); ?></h3>
            <p class="entry-content"><?php echo out($item['description']); ?></p>
        <?php } else { ?>
            <h3 class="entry-title">
                <a href="<?php echo out($item['url']); ?>"><?php echo out($item['title']); ?></a> <?php echo out($item['pdfInfo']); ?>
            </h3>
            <p class="entry-content"><?php echo out($item['description']); ?></p>
        <?php }
    } ?>

    <p><a href="#" class="top">Top</a></p>
</div>
