<?php
/**
 * app/views/news/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'News'));
$this->partial('partial/banner', array('banner' => $data['banner']));
?>
<div id="main-body">
    <div class="paging"><span class="nextprev">&laquo; Previous</span><span class="nextprev">Next &raquo;</span></div>

    TODO: get news

    <div class="paging"><span class="nextprev">&laquo; Previous</span><span class="nextprev">Next &raquo;</span></div>

    <p><a href="#" class="top">Top</a></p>
</div>
