<?php
/**
 * app/views/news/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
header('Content-Type: text/xml');
echo '<?xml version="1.0"?>';
?>
<rss version="2.0">
<channel>
<title>Staff Intranet: Announcements</title>
<link>http://intranet.local//announcements.php</link>
<description>Library of Congress Announcements</description>
<language>en-us</language>
<pubDate>Tue, 07 Oct 2014 11:00:39 -0400</pubDate>
<lastBuildDate>Wed, 31 Dec 1969 19:00:00 -0500</lastBuildDate>
<docs>http://blogs.law.harvard.edu/tech/rss</docs>
<managingEditor>noreply@loc.gov</managingEditor>
<webMaster>noreply@loc.gov</webMaster>
</channel>
</rss>
