<?php
/**
 * app/views/maintenance/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'Server Maintenance'));
?>
<div id="main-body">
    <p>Please be advised that the Staff Intranet is under going Server Maintenance at this time. We hope to have the site up and running momentarily.</p>

    <p>Also, please be advised that the error message above is probably false and the link below is useless. Have a nice day.</p>

    <p><a href="#" class="top">Top</a></p>
</div>
