<?php
/**
 * app/views/link-of-the-week/submitted.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'Library Link of the Week'));
$this->partial('partial/banner', array('banner' => $data['banner']));
?>
<div id="main-body">
    <h3 class="alt">Thank You!</h3>
    <p class="black">
        We appreciate your submission to the Library link of the week. While we can only feature one
        link each week, we'll post all appropriate submissions on our Link of the
        <a href="/link-of-the-week" title="Link of the Week Archives Page">Week Archives page</a>,
        and your suggestion may be featured soon. Keep those suggestions coming!
    </p>

    <p><a href="#" class="top">Top</a></p>
</div>
















