<?php
/**
 * app/views/link-of-the-week/suggest.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'Library Link of the Week'));
$this->partial('partial/banner', array('banner' => $data['banner']));
?>
<div id="main-body">
    <h2>Suggest Your Favorite Link</h2>
    <p class="black">Know of a hidden gem on the staff intranet or LOC public site? Share your knowledge with your Library peers.</p>

    <?php if (!empty($errors)) {
        echo '<ul class="error-msg">';
        foreach ($errors as $error) {
            echo '<li>' . out(ucwords($error)) . '</li>';
        }
        echo '</ul>';
    } ?>

    <form class="linksubmit" method="post">
        <p><em>All fields required*</em></p>
        <label for="title"><em>*</em> Title </label>
        <input type="text" id="title" name="title" value="<?php echo out($data['link']->title); ?>" tabindex="1" />
        <label for="url"><em>*</em> URL <span>(Library of Congress Websites Only Please)</span></label>
		<input type="text" id="url" name="url" value="<?php echo out($data['link']->url); ?>" tabindex="2" />
		<label for="description"><em>*</em> Describe the Resource <span></span></label>
		<textarea id="description" rows="5" cols="20" name="description" tabindex="3"><?php echo out($data['link']->description); ?></textarea>
		<label for="yourname"><em>*</em> Your Name</label>
		<input type="text" id="yourname" name="submitter" tabindex="4" value="<?php echo out($data['link']->submitter); ?>"/><br />
		<input class="button" type="submit" value="Submit" tabindex="5" />
		<input class="button" type="button" onclick="ClearLOWSuggestForm();" value="Clear" tabindex="6" />
	</form>

    <p><a href="#" class="top">Top</a></p>
</div>
