<?php
/**
 * app/views/forms/index.phtml
 *
 * PHP Version 5.3
 *
 * @package   Views
 * @author    aidan lydon <alyo@loc.gov>
 * @copyright 2014 The Library of Congress
 * @license   Copyright 2014 The Library of Congress
 * @version   $Id:$
 * @link      TBD
 * @since     Sept 24, 2014
 */
$this->partial('partial/head', array('head' => 'Forms'));
?>
<div id="main-body">
    <h2 class="title-alt">Library Forms Inventory</h2>
    <ul>
        <li><a href="http://www.loc.gov/staff/iss/eforms.html">Office Systems Services (OSS), Integrated Support Services Forms</a> - This page, compiled by the Records Management Section (RMS), Office Systems Services division, Integrated Support Services directorate, is developing a complete listing of all Library forms.  RMS will continue to add fillable forms, as they are completed, to this website.</li>
    </ul>

    <h2 class="title-alt">Division &amp; Support Unit Form Pages</h2>
    <ul>
        <li><a href="http://www.loc.gov/staff/ls/forms/index.html">Library Services Forms Page</a></li>
        <li><a href="http://www.loc.gov/staff/osi/staff/forms.html">Office of Strategic Initiatives Forms</a></li>
        <li><a href="http://www.loc.gov/staff/iss/webforms.html">Integrated Support Services Forms</a></li>
        <li><a href="http://www.loc.gov/staff/aba/forms2/lsforms2.html">Acquisitions and Bibliographic Access Directorate Forms (ABA)</a></li>
        <li><a href="http://www.loc.gov/staff/specialevents/procedures/">Office of Special Events and Public Programs Forms</a></li>
    </ul>

    <hr />

    <h2 class="title-alt"> Money, Pay &amp; Benefits</h2>
    <ul>
        <li><a href="http://www.loc.gov/staff/ocfo/systems/forms.html">Financial &amp; Planning Systems Momentum Forms</a></li>
        <li><a href="http://www.loc.gov/staff/hr/webta.html">HR's Web TA related forms</a> - Includes forms to donate and receive annual leave, alternative work schedule and advance sick leave forms</li>
    </ul>

    <h2 class="title-alt">Multimedia</h2>
    <ul>
        <li><a href="http://www.loc.gov/staff/its/MultimediaGroupRequestForm.php">Multimedia Request Form</a></li>
        <li><a href="http://www.loc.gov/staff/its/ipf.html">Permission and Release for Cybercasting</a></li>
        <li><a href="http://www.loc.gov/staff/core/working_with_pao/calendar_form.php">LOC Calendar Submission Form</a></li>
        <li><a href="http://www.loc.gov/staff/core/working_with_pao/photo_request_form.php">LOC Photographic Services Request Form</a></li>
    </ul>

    <h2 class="title-alt">Parking</h2>
    <ul>
        <li><a href="http://rs21n.loc.gov/mid-tier/forms/rs21n/PPO:Parking+Program+Start:PS/Parking+Program+Office/?usertimezone=America%2FDetroit&cacheid=9a88c2fe">Parking Permit Application</a></li>
    </ul>

    <h2 class="title-alt">Research Resources</h2>
    <ul>
        <li><a href="http://www.loc.gov/staff/cmd/specialsearch/sssstaff_form.php">Request for Special Search</a></li>
    </ul>

    <h2 class="title-alt">Reserve Rooms</h2>
    <ul>
        <li><a href="http://www.loc.gov/staff/cld/classroom-reservations/index.html">Center for Learning and Development Services Forms (classroom reservations, course registration forms)</a></li>
        <li><a href="http://www.loc.gov/staff/idt/classroomreservationform.php">Request an Instructional Design and Training Classroom</a></li>
    </ul>

    <h2 class="title-alt">Resident Research Programs</h2>
    <ul>
        <li><a href="http://www.loc.gov/loc/kluge/docs/klugeapp-generic.pdf">Staff Fellowships Application Form</a></li>
    </ul>

    <h2 class="title-alt">Web</h2>
    <ul>
        <li><a href="http://www.loc.gov/staff/webproduction/practices/">Web Production Portal Forms</a></li>
    </ul>

    <hr />

    <h2 class="title-alt">Non-LC Forms</h2>
    <ul>
        <li><a href="http://www.opm.gov/forms/index.asp" target="_blank" class="external" title="External link: http://">OPM Government Forms<span> (external link)</span></a></li>
    </ul>

    <p><a href="#" class="top">Top</a></p>
</div>
