<?php
/**
 * app/views/index.phtml - main layout file
 *
 * @package Layouts
 * @author  aidan lydon <aidanlydon@gmail.com>
 */
?>
<!DOCTYPE html>
<html>
<head>
    <title>phalcon base project</title>

    <meta http-equiv="Content-Language" content="en-us" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="/favicon.ico" />

    <link rel="stylesheet" media="all" type="text/css" href="/css/style.css" />

    <script type="text/javascript" src="/js/jquery.js"></script>
</head>
<body>
    <?php echo $this->getContent(); ?>
</body>
</html>
